stages:          # List of stages for jobs, and their order of execution
  - build
  - UnitTests
  - test  
  - deploy
  - release

variables:
  RELEASE_VERSION: "v1.0"  # Définir la version initiale

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

phpunit:
  image: php:7.4-apache
  stage: UnitTests
  script:
    - php bin/phpunit --filter=testcomputeTVAFoodProduct2
    - php bin/phpunit --filter=testcomputeTVAFoodProduct
    - php bin/phpunit --filter=testcomputeOtherTVAFoodProduct

lint-test-job:
  stage: test    
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

release-job:
  stage: release
  script:
    - echo "Creating release..."
    - echo "Incrementing release version..."
    - export RELEASE_VERSION=$(echo $RELEASE_VERSION | awk -F '.' '{$NF = $NF + 1;} 1' OFS='.')
    - git tag $RELEASE_VERSION  # Création du tag avec la nouvelle version
    - echo "Release successfully created and tagged as $RELEASE_VERSION."

