stages:
  - build
  - UnitTests
  - CodeCoverage  
  - release
  - deploy
  - pages

variables:
  RELEASE_MAJOR: 1
  RELEASE_MINOR: 0
  RELEASE_PATCH: $CI_PIPELINE_IID
  RELEASE_VERSION: "v.$RELEASE_MAJOR.$RELEASE_MINOR.$RELEASE_PATCH"

build-job:   
  stage: build  
  script:
  - echo "Installing Symfony CLI..."
  - wget https://get.symfony.com/cli/installer -O - | bash
  - mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
  - echo "Symfony CLI installed."

phpunit:
  image: php:7.4-apache
  stage: UnitTests
  script:
    - php bin/phpunit --filter=testcomputeTVAFoodProduct2
    - php bin/phpunit --filter=testcomputeTVAFoodProduct
    - php bin/phpunit --filter=testcomputeOtherTVAFoodProduct

lint-test-job:
  image : php:7.4-apache
  stage: CodeCoverage    
  script:
    - echo "Linting code... This will take about 10 seconds."
    - php bin/phpunit --coverage-html public/test-coverage

deploy-job:
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  
  script:
    - echo "running release_job for $TAG"
  release:                                        
    tag_name: "$RELEASE_VERSION"
    description: "$RELEASE_VERSION"
    ref: '$CI_COMMIT_SHA'

pages:
  stage: pages
  script:
    - echo "Building and deploying GitLab Pages..."
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - echo "GitLab Pages built and deployed successfully."

  artifacts:
    paths:
      - public/