stages:          # List of stages for jobs, and their order of execution
  - build
  - UnitTests
  - test  
  - release_job
  - deploy

variables:
  RELEASE_VERSION: "v1.0"

build-job:       
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

phpunit:
  image: php:7.4-apache
  stage: UnitTests
  script:
    - php bin/phpunit --filter=testcomputeTVAFoodProduct2
    - php bin/phpunit --filter=testcomputeTVAFoodProduct
    - php bin/phpunit --filter=testcomputeOtherTVAFoodProduct

lint-test-job:
  stage: test    
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v0.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'v0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.

